[gh-pages] Fix trailing slash -> module not found
fix trailing slash cause
Uncaught Error: Cannot find module './components/windows/Button/index.html'.